/* ============================================================
 * version.h  —  WindTrans firmware version
 *
 * AUTO-GENERATED by scripts/hooks/pre-commit.
 * Do NOT edit manually — changes will be overwritten on next commit.
 * To bump MAJOR or MINOR, edit FW_VERSION_MAJOR / FW_VERSION_MINOR
 * in scripts/hooks/pre-commit and commit once to take effect.
 * ============================================================ */
#ifndef VERSION_H
#define VERSION_H

#define FW_VERSION_MAJOR  1
#define FW_VERSION_MINOR  1
#define FW_VERSION_BUILD  47

#define FW_VERSION        "1.1.047"

#endif /* VERSION_H */
